---
name: etcd-acceptance

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: etcd-acceptance
  version: latest
- name: kubo-etcd
  version: latest
- name: bosh-dns
  version: latest

features:
  use_dns_addresses: true

addons:
- name: bosh-dns
  include:
    stemcells:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      cache:
        enabled: true

instance_groups:
- name: etcd-acceptance
  lifecycle: errand
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: etcd-bosh-dns-aliases
    release: kubo-etcd
    consumes:
      etcd: {from: etcd_server, deployment: etcd}
  - name: read-availability-during-recreate
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd_server, deployment: etcd}
    properties:
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      tls: ((tls-etcd-client))
      uaa_url: ((uaa-url))
      turbulence_ca: ((turbulence-ca))
  - name: read-availability-during-network-partition
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd_server, deployment: etcd}
    properties:
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      tls: ((tls-etcd-client))
      uaa_url: ((uaa-url))
      turbulence_ca: ((turbulence-ca))

update:
  serial: true
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
